### ISSUE TITLE
No selectors for CSS?

### ISSUE THREAD

**Issue by syranide** [reactjs/react-future#13]
https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/Inline%20Style%20Extension.md#no-selectors

What about hover (etc) styles for descendants? This seems like a major issue with the current approach, unless I'm missing something.

```
.button:hover > .label {
  top: 1px;
  font-weight: bold;
}
```

Also, if you're really intending for these to be supplied as styles, as opposed to classNames, I'm pretty sure that would destroy the overall performance.

**Comment by ladyborg** [comment]
@vjeux that doesn't seem very elegant... browsers already have functionality implemented for managing hover state in css, why not tap into what's already there by default anyway?

It seems to me that there are probably multiple ways of simply providing some decent JS sugar to utilize things like `:hover`. Obviously there are lots of react styling frameworks now, but it doesn't seem totally unreasonable to expect a 'React way' of doing this included in the library that we can all (read: 'most') agree on... lol

**Comment by geyang** [comment]
What about for layout options, such as flex box and position relative? Say I want to have a container element with the `display: flex-box` and want the child elements to have `flex: 0 0 auto`. I would prefer to have these styles applied by the parent element and be grouped together, instead of splitting it between the parent and the child.
