### ISSUE TITLE
Inputs aren't generic across different backends

### ISSUE THREAD

**Issue by spicyj** [reactjs/react-future#2]
The current recommended way to get the value of an input is

```
this.refs.myInput.getDOMNode().value
```

or in an event handler,

```
e.target.value
```

Both of these are DOM-specific. Ideally this wouldn't involve talking to the DOM directly – the current way makes the React abstraction leakier and prevents the same component API from being supported against multiple backends.

We could make something like `this.refs.myInput.getValue()` work, but perhaps there's something cleaner we can build?

**Comment by daedelus-j** [comment]
:+1:

**Comment by nmn** [comment]
So this issue was raised way before React-Native was annouced, so I guess I was being a little myopic.

At this point I think having a generic way to get and set values would be a great idea. That said, it would necessarily need to work with objects, kind of like setState.

Many components can have many different kinds of data that they store, returns and fire events for.

**Comment by moimikey** [comment]
I was initially confused by the two different means of actually getting an input value between the two during a code review (we're doing some investigatory spikes with React). aside from `this.refs.myInput.getDOMNode().value` seeming more like an abstraction, are there any caveats between that and `e.target.value`, or are they indefinitely 1-to-1? a `getValue` method seems to most intuitive, but my lack of core knowledge makes that a brittle opinion.

**Comment by sebmarkbage** [comment]
I don't think we'll actually end up doing this for built-ins since they will return the actual DOM node and therefore, we can't new methods to it. Instead, a generic version would use a getter.

I'll close this out because this isn't actionable, but feel free to reboot the conversation with a different proposal if we need more unification.
