### ISSUE TITLE
Just a silly question

### ISSUE THREAD

**Issue by anterokarttunen** [reactjs/react-future#29]
Will you guys ever do the same thing like Google did on angularjs..?
..angularjs 2.0 was a total rewrite and if youre using 1.x your in deep shieet. Luckily I didn't have anything angular in production.

For me at least, its very important that IF I choose to use something, going forward shouldn't mean discarding all the stuff you have done. I understand that of course one must do stuff to go on.. but, a total rewrite.. ewww.

**Comment by syranide** [comment]
I don't work at FB, but as far as I'm aware they are fully committed at FB and IG so it's not something they would do lightly, whereas Google is basically just using Angular for internal dev tools. More than that React boils down to "immediate mode rendering", it's not a new or at all complicated subject and they've already proven that it actually works really well in practice even for the largest of large-scale apps. So the foundation is solid, everything else that is being developed is basically "opt-in" features on-top of that, so even if they hypothetically walk down a catastrophically bad path it wouldn't be fundamentally broken and most of your components would be salvageable one way or another (again, hypothetical scenario).

So for me, React is the first and only framework that I've felt actually got it right (enough) that I've felt confident professionally committing to knowing that even when "another framework" inevitably comes around that React will still be a solid foundation and will continue to be supported.

**Comment by slorber** [comment]
+1

React is simple, Angular is not so. As far as I know, React components can be somehow compared with Angular directives with a template and an isolate scope in term of usage / component composability (even if the inner workings are really different). 

Angular 2.0 is removing things like Controller.
Release after release, React keeps being simple and does not really add or remove many things, the changes are just implementation details that are well explained/understood by the community.

React is just a first successful implementation of a simple purely functional concept: f(Data) = View
Basically f(Json) = Dom
But this is valid for any UI technology (see React Native). 
You could have f(JavaPojo) = Swing UI too!

I don't think React will ever change its core to solve other problems, but is a solid fundation for more advanced frameworks to build on it. As we don't need to worry anymore about that transformation from state to UI, we see more and more frameworks that have opiniated ways to manage the state of your application (ie most Flux implementations). You should be more concerned about a total rewrite of these frameworks than a total rewrite of React as this field is not yet mature.

Even if React were to be rewritten, the current API is pretty well designed and I don't think it would have to change so much from vX to vX+1.

I'm using React since 0.5, developping a framework, a mobile app, a clipper and a browser app with React. There are breaking changes from release to release but I've never seen anything unmanageable. Breaking changes are introduced progressively. Most migrations took less than half a day for a medium sized SPA.

By the way, if you are satisfied with Angular 1.x, you can still stick with it. Being maintained is not such a big deal if the product works great. If the current version of React was not maintained I would still use it.

**Comment by anterokarttunen** [comment]
Hmm, coulda continue using angularjs 1.x but I have this bad gut feeling about it. 

Looks like I shall put my efforts on evaluating reactjs and that flux thingie for our production apps frontend facelift :)

Cheers!
