### ISSUE TITLE
Passing styles around should be discouraged

### ISSUE THREAD

**Issue by chrislloyd** [reactjs/react-future#44]
From: https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/04%20-%20Inline%20Styles.md#pass-styles-around

This pattern promotes a leaky abstraction where components are unable to fully understand their styling unless they also know their call-sites. It's the stylistic equivalent of `PropTypes.any`. If components need to style their children, they should do so through well defined interfaces. One possible compromise is to have the `StylePropType` helper validate certain properties and values.

**Comment by fdecampredon** [comment]
In a custom library of mine (not open source yet) I implemented a little feature that I find interesting for this problem.
the library use a 'styles' property on ReactDOMComponent to apply a a set of styles : 
```javascript
var styles = StyleSheet.create({
  myDiv: {
    padding: 20
  }
});

class MyComponent extends React.Component {
  render () {
    <div styles={styles.myDiv} />
  }
}
 
```
Nothing new here, but I also let styles being retrieved from the owner component if the dom component is the root node of the component.
So for example : 

```javascript
var styles = StyleSheet.create({
  myDiv: {
    padding: 20
  },
  myComponent: {
    marginTop: 20
  }
});

class MyComponent extends React.Component {
  render () {
    <div styles={styles.myDiv} />
  }
}

class ParentComponent extends React.Component {
  render() {
    <MyComponent styles={styles.myComponent}  />
  }
}

```
Here the `div` will have both styles `paddingTop: 20` and `marginTop: 20`. 
I find it interesting because passing style around manually can be bothersome and you can without caution easily erase some styles from your component.
